<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <Configurations>Debug;Release;Ravi;Testing;Subodh</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\logo.png" />
    <None Remove="Assets\opn.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="libphonenumber-csharp" Version="9.0.31" />
    <PackageReference Include="MahApps.Metro.IconPacks.BootstrapIcons" Version="6.2.1" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.7" />
    <PackageReference Include="MySql.Data" Version="9.7.0" />
    <PackageReference Include="MySqlBackup.NET" Version="2.7.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\opn.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <None Update="SetupFiles\CRM.bmp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="SetupFiles\eula.rtf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="SetupFiles\Offline-Icon.bmp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="SetupFiles\Offline.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="SetupFiles\Online-Icon.bmp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="SetupFiles\Online.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="SetupFiles\SofricCert.cer">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="SetupFiles\tlogo.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
